global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'url-shortener'
    dns_sd_configs:
      - names:
          - 'url-shortener-api'
        type: 'A'
        port: 8080
    metrics_path: '/metrics'
    scrape_interval: 5s
